/**
 * Build metadata (M11 §41): generated by scripts/write-build-info.mjs at
 * packaging time; falls back to app version only in dev runs.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

let info = null;
try {
  info = JSON.parse(readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'build-info.json'), 'utf8'));
} catch { /* dev run without generated metadata */ }

export function buildInfo() {
  return {
    version: info?.version ?? 'dev',
    buildId: info?.buildId ?? null,
    commit: info?.commit ?? null,
    buildDate: info?.buildDate ?? null,
    configuration: info?.configuration ?? 'development',
    platform: 'windows-x64',
  };
}
